### PR TITLE
Fix commonjs import under certain TypeScript configuration

### PR DESCRIPTION
**Pull request by stanley2058**
With the current packaging settings, the import statement on the umd file will be treated as an ESM `import` instead of an `require` statement.

```
/node_modules/.pnpm/ts-node@10.9.2_@types+node@22.5.5_typescript@5.6.2/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/.pnpm/y-lwwmap@0.1.9/node_modules/y-lwwmap/dist/LWWMap.js from /index.ts not supported.
LWWMap.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename LWWMap.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /node_modules/.pnpm/y-lwwmap@0.1.9/node_modules/y-lwwmap/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/node_modules/.pnpm/ts-node@10.9.2_@types+node@22.5.5_typescript@5.6.2/node_modules/ts-node/dist/index.js:851:20)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (/index.ts:27:20) {
  code: 'ERR_REQUIRE_ESM'
}
```

For more details, see https://github.com/stanley2058/y-lwwmap-cjs-repro.

The above error implies that because the `type` is set to `module` in `package.json` and the `require` field in exports is set to a filename ending with `.js`, it's being treated as an ESM module.
https://github.com/rozek/y-lwwmap/blob/f071aa5be60d440cc5cb156a9f3868ca4cf5e9c9/package.json#L5
https://github.com/rozek/y-lwwmap/blob/f071aa5be60d440cc5cb156a9f3868ca4cf5e9c9/package.json#L12

With this PR, I've added a separate CommonJS build for Node to resolve the issue above. I also replaced the `Observable` import with a module-agnostic one to allow automatic CJS/ESM interop. (According to https://github.com/dmonad/lib0?tab=readme-ov-file#using-lib0, import path without `.js` will automatically resolve to the correct one)

With the fix in this PR, the above repro can run without error:
```
❯ pnpm run ts-node

> y-lwwmap-test@1.0.0 ts-node /y-lwwmap-test
> ts-node .

world
```

### CODE REVIEW

**Comment by rozek** [comment]
Thank you very much for your work!

**Review by rozek — APPROVED** [review]

**Comment by rozek** [comment]
I'm (slowly) brushing up my builds to work in more environments. After merging your changes, I've just "repaired" this one as well: if you like, you may test the new configuration (it should run server-side and browser-side with and without a bundler - even within Svelte)

**Comment by stanley2058** [comment]
I've tried the latest build, and everything works as intended. Great work! :tada: :tada:

**Comment by rozek** [comment]
Thank you very much for your feedback!

**Pull request merged**
